from django.core.management.base import BaseCommand
from books.models import Book


class Command(BaseCommand):
    help = "Seed initial books"

    def handle(self, *args, **options):
        books_data = [
                {
                    "title": "Dune",
                    "author": "Frank Herbert",
                    "genre": "Sci-Fi",
                    "description": "Epic tale of politics, religion, and ecology on a desert planet.",
                    "publication_year": 1965,
                },
                {
                    "title": "1984",
                    "author": "George Orwell",
                    "genre": "Dystopian",
                    "description": "Totalitarian surveillance state and loss of personal freedom.",
                    "publication_year": 1949,
                },
                {
                    "title": "The Great Gatsby",
                    "author": "F. Scott Fitzgerald",
                    "genre": "Classic",
                    "description": "A novel about the American dream and the Roaring Twenties.",
                    "publication_year": 1925,
                },
                {
                    "title": "To Kill a Mockingbird",
                    "author": "Harper Lee",
                    "genre": "Classic",
                    "description": "A story of racial injustice and the loss of innocence in the American South.",
                    "publication_year": 1960,
                },
                {
                    "title": "Pride and Prejudice",
                    "author": "Jane Austen",
                    "genre": "Romance",
                    "description": "A romantic novel of manners.",
                    "publication_year": 1813,
                },
                # Additional 45 popular books:
                {
                    "title": "The Lord of the Rings",
                    "author": "J.R.R. Tolkien",
                    "genre": "Fantasy",
                    "description": "Epic quest to destroy a powerful ring in a richly imagined world.",
                    "publication_year": 1954,
                },
                {
                    "title": "Harry Potter and the Sorcerer's Stone",
                    "author": "J.K. Rowling",
                    "genre": "Fantasy",
                    "description": "A young boy discovers he is a wizard and enters a magical world.",
                    "publication_year": 1997,
                },
                {
                    "title": "Animal Farm",
                    "author": "George Orwell",
                    "genre": "Satire",
                    "description": "Allegory of revolution and corruption where farm animals revolt.",
                    "publication_year": 1945,
                },
                {
                    "title": "The Catcher in the Rye",
                    "author": "J.D. Salinger",
                    "genre": "Coming-of-Age",
                    "description": "A disillusioned teenager's journey through New York City.",
                    "publication_year": 1951,
                },
                {
                    "title": "Brave New World",
                    "author": "Aldous Huxley",
                    "genre": "Dystopian",
                    "description": "A futuristic society obsessed with pleasure and conformity.",
                    "publication_year": 1932,
                },
                {
                    "title": "Fahrenheit 451",
                    "author": "Ray Bradbury",
                    "genre": "Dystopian",
                    "description": "A future where books are banned and firemen burn them.",
                    "publication_year": 1953,
                },
                {
                    "title": "Jane Eyre",
                    "author": "Charlotte Brontë",
                    "genre": "Gothic Romance",
                    "description": "An orphan's journey to independence and love amid secrets.",
                    "publication_year": 1847,
                },
                {
                    "title": "The Hobbit",
                    "author": "J.R.R. Tolkien",
                    "genre": "Fantasy",
                    "description": "A reluctant hobbit joins dwarves on a treasure-seeking adventure.",
                    "publication_year": 1937,
                },
                {
                    "title": "Lord of the Flies",
                    "author": "William Golding",
                    "genre": "Allegory",
                    "description": "Boys stranded on an island descend into savagery.",
                    "publication_year": 1954,
                },
                {
                    "title": "The Handmaid's Tale",
                    "author": "Margaret Atwood",
                    "genre": "Dystopian",
                    "description": "A woman's struggle in a totalitarian regime that subjugates women.",
                    "publication_year": 1985,
                },
                {
                    "title": "Frankenstein",
                    "author": "Mary Shelley",
                    "genre": "Gothic Horror",
                    "description": "A scientist creates life with tragic consequences.",
                    "publication_year": 1818,
                },
                {
                    "title": "The Little Prince",
                    "author": "Antoine de Saint-Exupéry",
                    "genre": "Philosophical",
                    "description": "A young prince's travels and reflections on life and love.",
                    "publication_year": 1943,
                },
                {
                    "title": "Moby-Dick",
                    "author": "Herman Melville",
                    "genre": "Adventure",
                    "description": "A captain's obsessive hunt for a giant white whale.",
                    "publication_year": 1851,
                },
                {
                    "title": "Crime and Punishment",
                    "author": "Fyodor Dostoevsky",
                    "genre": "Psychological",
                    "description": "A student's moral torment after committing murder.",
                    "publication_year": 1866,
                },
                {
                    "title": "Wuthering Heights",
                    "author": "Emily Brontë",
                    "genre": "Gothic Romance",
                    "description": "A tale of passionate, destructive love on the moors.",
                    "publication_year": 1847,
                },
                {
                    "title": "The Alchemist",
                    "author": "Paulo Coelho",
                    "genre": "Philosophical",
                    "description": "A shepherd's journey to follow his personal legend.",
                    "publication_year": 1988,
                },
                {
                    "title": "One Hundred Years of Solitude",
                    "author": "Gabriel García Márquez",
                    "genre": "Magical Realism",
                    "description": "Multi-generational saga of a family in a mythical town.",
                    "publication_year": 1967,
                },
                {
                    "title": "The Grapes of Wrath",
                    "author": "John Steinbeck",
                    "genre": "Historical Fiction",
                    "description": "A family's migration during the Great Depression.",
                    "publication_year": 1939,
                },
                {
                    "title": "Catch-22",
                    "author": "Joseph Heller",
                    "genre": "Satire",
                    "description": "Absurdities of war and bureaucracy in WWII.",
                    "publication_year": 1961,
                },
                {
                    "title": "Slaughterhouse-Five",
                    "author": "Kurt Vonnegut",
                    "genre": "Sci-Fi",
                    "description": "A man's time-traveling experiences during and after war.",
                    "publication_year": 1969,
                },
                {
                    "title": "The Bell Jar",
                    "author": "Sylvia Plath",
                    "genre": "Semi-Autobiographical",
                    "description": "A young woman's mental health struggles.",
                    "publication_year": 1963,
                },
                {
                    "title": "Invisible Man",
                    "author": "Ralph Ellison",
                    "genre": "Literary Fiction",
                    "description": "A Black man's search for identity in racist America.",
                    "publication_year": 1952,
                },
                {
                    "title": "Beloved",
                    "author": "Toni Morrison",
                    "genre": "Historical Fiction",
                    "description": "A mother's haunting past after slavery.",
                    "publication_year": 1987,
                },
                {
                    "title": "The Color Purple",
                    "author": "Alice Walker",
                    "genre": "Epistolary",
                    "description": "A woman's empowerment amid abuse and racism.",
                    "publication_year": 1982,
                },
                {
                    "title": "Anna Karenina",
                    "author": "Leo Tolstoy",
                    "genre": "Literary Fiction",
                    "description": "Tragic tale of love, infidelity, and society.",
                    "publication_year": 1878,
                },
                {
                    "title": "Don Quixote",
                    "author": "Miguel de Cervantes",
                    "genre": "Satire",
                    "description": "A delusional knight's adventures in a realistic world.",
                    "publication_year": 1605,
                },
                {
                    "title": "The Odyssey",
                    "author": "Homer",
                    "genre": "Epic",
                    "description": "A hero's long journey home after the Trojan War.",
                    "publication_year": -800,  # Approximate BCE date
                },
                {
                    "title": "Great Expectations",
                    "author": "Charles Dickens",
                    "genre": "Bildungsroman",
                    "description": "An orphan's rise and moral growth.",
                    "publication_year": 1861,
                },
                {
                    "title": "A Tale of Two Cities",
                    "author": "Charles Dickens",
                    "genre": "Historical Fiction",
                    "description": "Love and sacrifice during the French Revolution.",
                    "publication_year": 1859,
                },
                {
                    "title": "The Adventures of Huckleberry Finn",
                    "author": "Mark Twain",
                    "genre": "Adventure",
                    "description": "A boy's raft journey down the Mississippi with moral lessons.",
                    "publication_year": 1884,
                },
                {
                    "title": "Alice's Adventures in Wonderland",
                    "author": "Lewis Carroll",
                    "genre": "Fantasy",
                    "description": "A girl's surreal adventures in a nonsensical world.",
                    "publication_year": 1865,
                },
                {
                    "title": "The Hitchhiker's Guide to the Galaxy",
                    "author": "Douglas Adams",
                    "genre": "Sci-Fi Comedy",
                    "description": "Absurd galactic adventures after Earth is destroyed.",
                    "publication_year": 1979,
                },
                {
                    "title": "The Hunger Games",
                    "author": "Suzanne Collins",
                    "genre": "Dystopian",
                    "description": "A girl fights for survival in a televised death match.",
                    "publication_year": 2008,
                },
                {
                    "title": "The Book Thief",
                    "author": "Markus Zusak",
                    "genre": "Historical Fiction",
                    "description": "A girl's life in Nazi Germany, narrated by Death.",
                    "publication_year": 2005,
                },
                {
                    "title": "The Fault in Our Stars",
                    "author": "John Green",
                    "genre": "Young Adult",
                    "description": "Two teens with cancer fall in love.",
                    "publication_year": 2012,
                },
                {
                    "title": "Life of Pi",
                    "author": "Yann Martel",
                    "genre": "Adventure",
                    "description": "A boy's survival at sea with a Bengal tiger.",
                    "publication_year": 2001,
                },
                {
                    "title": "The Girl with the Dragon Tattoo",
                    "author": "Stieg Larsson",
                    "genre": "Mystery Thriller",
                    "description": "A journalist and hacker investigate a decades-old disappearance.",
                    "publication_year": 2005,
                },
                {
                    "title": "A Game of Thrones",
                    "author": "George R.R. Martin",
                    "genre": "Fantasy",
                    "description": "Political intrigue and war in a medieval-inspired world.",
                    "publication_year": 1996,
                },
                {
                    "title": "The Old Man and the Sea",
                    "author": "Ernest Hemingway",
                    "genre": "Literary Fiction",
                    "description": "An aging fisherman's epic battle with a giant marlin.",
                    "publication_year": 1952,
                },
                {
                    "title": "Of Mice and Men",
                    "author": "John Steinbeck",
                    "genre": "Novella",
                    "description": "Two migrant workers' dream during the Great Depression.",
                    "publication_year": 1937,
                },
                {
                    "title": "The Outsiders",
                    "author": "S.E. Hinton",
                    "genre": "Young Adult",
                    "description": "Rivalry between teen gangs in 1960s Oklahoma.",
                    "publication_year": 1967,
                },
                {
                    "title": "Charlotte's Web",
                    "author": "E.B. White",
                    "genre": "Children's",
                    "description": "A pig and spider's friendship on a farm.",
                    "publication_year": 1952,
                },
                {
                    "title": "The Lion, the Witch and the Wardrobe",
                    "author": "C.S. Lewis",
                    "genre": "Fantasy",
                    "description": "Children discover a magical world through a wardrobe.",
                    "publication_year": 1950,
                },
            ]        
        # Bulk update or create
        for data in books_data:
            Book.objects.get_or_create(title=data["title"], defaults=data)
        
        
        self.stdout.write(self.style.SUCCESS(f"Seeded {len(books_data)} books"))
