# Generated by Django 5.2.4 on 2026-02-20 20:15

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # This is the equivalent of: CREATE EXTENSION IF NOT EXISTS vector;
        VectorExtension(),
    ]